---
deployment:
  tasks:
    - export DEPLOYPATH=/home/systemwafragulf/public_html/
    - /bin/cp -R . $DEPLOYPATH
    - cd $DEPLOYPATH && php artisan config:clear
    - cd $DEPLOYPATH && php artisan config:cache
    - cd $DEPLOYPATH && php artisan route:clear
    - cd $DEPLOYPATH && php artisan route:cache
    - cd $DEPLOYPATH && php artisan view:clear
    - cd $DEPLOYPATH && php artisan migrate --force
